name: Repository Mirroring

on:
  push:
    branches:
      - main

jobs:
  mirror_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          destination_repository:
            git@github.com:EpitechPromo2028/B-DOP-200-LYN-2-1-chocolatine-bebey-dooh.lucresse-desiree-grace.git
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
